name: Run CI Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: 1-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          1-${{ runner.os }}-yarn-
    - name: Run CI
      run: |
        set -euo pipefail
        JOBS=$(nproc) yarn install --frozen-lockfile
        yarn run tsc
        yarn run format:ci
        yarn run eslint
        yarn run build
